Repository necrokochou/Primal-Black-Market, pull requests merged in 2025-07, with the labels that each got.

#125 Merge backend into main: modify env variables and bootstrap
  bootstrap.php
  utils/envSetter.util.php
Labels: enhancement

#138 backend-database-checkers: add .env.example
  .env.example
  utils/envSetter.util.php
Labels: enhancement

#137 backend-user-authentication: fixed user authentication variables
  handlers/auth.handler.php
  utils/auth.util.php
Labels: enhancement

#142 Sync main to database
  account
  assets/js/primal-register.js
  bindParam('
  execute()
  fetch()
  handlers/auth.handler.php
  handlers/register.handler.php
  prepare('SELECT
  staticData/dummies/users.staticData.php
  utils/auth.util.php
  utils/register.util.php
Labels: sync, merge last

#154 Sync main to backend
  account
  assets/js/auth.js
  assets/js/primal-register.js
  bindParam('
  execute()
  fetch()
  handlers/auth.handler.php
  handlers/email-check.handler.php
  handlers/logout.handler.php
  pages/login/index.php
  pages/register/index.php
  prepare('SELECT
  utils/auth.util.php
  utils/dbConnect.util.php
  utils/register.util.php
Labels: sync, merge last

#156 refactor: Reminder_Seeder notes.
  docs/Reminder_Seeder-Migrate-Reset.md
Labels: enhancement

#172 Backend feat: added cart and admin user delete functionality
  assets/js/cart.js
  assets/js/main.js
  assets/js/primal-admin.js
  assets/js/primal-body.js
  assets/js/primal-cart.js
  assets/js/primal-shop.js
  bootstrap.php
  components/productCard.component.php
  handlers/admin.handler.php
  handlers/auth.handler.php
  handlers/cart.handler.php
  index.php
  layouts/header.php
  pages/about/index.php
  pages/account/index.php
  pages/admin/index.php
  pages/cart/index.php
  pages/shop/index.php
  utils/DatabaseService.util.php
  utils/auth.util.php
  utils/cart.util.php
  utils/dbConnect.util.php
  utils/dbSeederPostgresql.util.php
  utils/productCard.util.php
  utils/register.util.php
Labels: enhancement

#166 FE:Feat(404): Added the error page.
  assets/css/primal-404.css
  assets/css/primal-body.css
  assets/js/primal-404.js
  errors/404.php
  index.php
  pages/about/index.php
  pages/account/index.php
  pages/admin/index.php
  pages/cart/index.php
  pages/login/index.php
  pages/register/index.php
  pages/shop/index.php
Labels: enhancement

#173 Sync main to frontend
  assets/css/primal-account.css
  assets/js/cart.js
  assets/js/main.js
  assets/js/primal-account.js
  assets/js/primal-admin.js
  assets/js/primal-body.js
  assets/js/primal-cart.js
  assets/js/primal-login.js
  assets/js/primal-shop.js
  bootstrap.php
  components/productCard.component.php
  docs/Reminder_Seeder-Migrate-Reset.md
  handlers/admin.handler.php
  handlers/auth.handler.php
  handlers/cart.handler.php
  handlers/emailCheck.handler.php
  handlers/logout.handler.php
  index.php
  layouts/header.php
  pages/about/index.php
  pages/account/index.php
  pages/admin/index.php
  pages/cart/index.php
  pages/login/index.php
  pages/shop/index.php
  utils/DatabaseService.util.php
  utils/auth.util.php
  utils/cart.util.php
  utils/dbConnect.util.php
  utils/dbSeederPostgresql.util.php
  utils/dbVerifyTables.util.php
  utils/productCard.util.php
  utils/register.util.php
Labels: sync, merge last

#174 Sync main to database
  assets/css/primal-account.css
  assets/css/primal-admin.css
  assets/images/bc.png
  assets/images/mc.png
  assets/images/pp.png
  assets/images/visa.png
  assets/js/cart.js
  assets/js/main.js
  assets/js/primal-account.js
  assets/js/primal-admin.js
  assets/js/primal-body.js
  assets/js/primal-cart.js
  assets/js/primal-login.js
  assets/js/primal-shop.js
  bootstrap.php
  clear_session.php
  components/productCard.component.php
  docs/Reminder_Seeder-Migrate-Reset.md
  handlers/admin.handler.php
  handlers/auth.handler.php
  handlers/cart.handler.php
  handlers/emailCheck.handler.php
  handlers/example.handler.php
  handlers/register.handler.php
  index.php
  layouts/footer.php
  layouts/header.php
  pages/about/index.php
  pages/account/index.php
  pages/admin/index.php
  pages/cart/index.php
  pages/login/index.php
  pages/logout/index.php
  pages/shop/index.php
  session_check.php
  staticData/dummies/feedbacks.staticData.php
  staticData/dummies/listings.staticData.php
  staticData/dummies/messages.staticData.php
  utils/DatabaseService.util.php
  utils/auth.util.php
  utils/cart.util.php
  utils/dbConnect.util.php
  utils/dbSeederPostgresql.util.php
  utils/dbVerifyTables.util.php
  utils/productCard.util.php
  utils/register.util.php
Labels: sync, merge last

#184 Sync main to backend
  assets/js/primal-admin.js
  composer.json
  database/purchase_history.model.sql
  database/users.model.sql
  pages/account/index.php
  staticData/dummies/cart.staticData.php
  staticData/dummies/listings.staticData.php
  staticData/dummies/purchase_history.staticData.php
  staticData/dummies/users.staticData.php
  staticData/pgTables.staticData.php
  utils/dbMigratePostgresql.util.php
  utils/dbResetPostgresql.util.php
  utils/dbSeederPostgresql.util.php
  utils/dbVerifyTables.util.php
Labels: sync

#189 Sync main to backend
  assets/css/homepage.css
  assets/css/primal-account.css
  assets/css/primal-registration.css
  assets/js/primal-account.js
  assets/js/primal-registration.js
  components/sellerProductModal.component.php
  database/users.model.sql
  handlers/account.handler.php
  handlers/auth.handler.php
  index.php
  pages/account/index.php
  pages/register/index.php
  pages/shop/index.php
  staticData/dummies/users.staticData.php
  test-checkboxes.html
  utils/DatabaseService.util.php
  utils/auth.util.php
  utils/dbResetPostgresql.util.php
  utils/dbSeederPostgresql.util.php
  utils/register.util.php
Labels: sync

#192 backend-acc-settings feat: added email functionality in login page
  assets/js/primal-login.js
  handlers/auth.handler.php
  pages/account/index.php
  pages/login/index.php
  utils/auth.util.php
Labels: enhancement

#199 backend-allen-fix refactor: changed date to timestamp in created_at
  assets/js/primal-admin.js
  utils/DatabaseService.util.php
  utils/register.util.php
Labels: enhancement

#197 Sync main to database
  assets/js/primal-account.js
  assets/js/primal-admin.js
  composer.json
  handlers/products.handler.php
  pages/admin/index.php
  utils/DatabaseService.util.php
  utils/register.util.php
Labels: sync

#201 Sync main to test-main
  assets/css/homepage.css
  assets/css/primal-account.css
  assets/css/primal-admin.css
  assets/css/primal-registration.css
  assets/css/primal-seller-modal.css
  assets/images/user-uploads/temp/.htaccess
  assets/js/cart.js
  assets/js/main.js
  assets/js/primal-account.js
  assets/js/primal-admin.js
  assets/js/primal-body.js
  assets/js/primal-cart.js
  assets/js/primal-login.js
  assets/js/primal-register.js
  assets/js/primal-seller-modal.js
  assets/js/primal-shop.js
  bootstrap.php
  components/productCard.component.php
  components/sellerProductModal.component.php
  composer.json
  create-upload-directory.sh
  database/purchase_history.model.sql
  database/users.model.sql
  docs/Reminder_Seeder-Migrate-Reset.md
  handlers/account.handler.php
  handlers/admin.handler.php
  handlers/auth.handler.php
  handlers/cart.handler.php
  handlers/products.handler.php
  index.php
  layouts/header.php
  pages/about/index.php
  pages/account/index.php
  pages/admin/index.php
  pages/cart/index.php
  pages/login/index.php
  pages/register/index.php
  pages/shop/index.php
  staticData/dummies/cart.staticData.php
  staticData/dummies/listings.staticData.php
  staticData/dummies/purchase_history.staticData.php
  staticData/dummies/users.staticData.php
  staticData/pgTables.staticData.php
  utils/DatabaseService.util.php
  utils/auth.util.php
  utils/cart.util.php
  utils/databaseHealthCheck.util.php
  utils/dbConnect.util.php
  utils/dbMigratePostgresql.util.php
  utils/dbResetPostgresql.util.php
  utils/dbSeederPostgresql.util.php
  utils/dbVerifyTables.util.php
  utils/envSetter.util.php
  utils/fixCategoriesDatabase.util.php
  utils/productCard.util.php
  utils/register.util.php
  utils/session.util.php
Labels: sync

#206 backend-purchase-history: Add purchase history feature
  assets/js/primal-cart.js
  handlers/cart.handler.php
  pages/account/index.php
  utils/cart.util.php
Labels: enhancement

#157 refactor: deleted feedbacks and messages sql.
  database/feedbacks.model.sql
  database/messages.model.sql
  utils/dbMigratePostgresql.util.php
  utils/dbResetPostgresql.util.php
  utils/dbSeederPostgresql.util.php
Labels: enhancement

#160 refactor: reminder seeder step 4
  docs/Reminder_Seeder-Migrate-Reset.md
Labels: enhancement
